apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrations
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: flyway
        image: redgate/flyway
        args: ["migrate"]
        volumeMounts:
        - name: sql-migrations
          mountPath: /flyway/sql
        - name: flyway-conf
          mountPath: /flyway/conf
        env:
        - name: DB_CONN
          value: "jdbc:postgresql://gke-pg-cluster-rw.pg-ns:5432/app"
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: gke-pg-cluster-app
              key: username
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gke-pg-cluster-app
              key: password
      restartPolicy: Never
      volumes:
      - name: sql-migrations
        gitRepo:
          repository: "https://github.com/SzymonKozl/irio_alerting_platform"
          directory: "server/db_migrations"
      - name: flyway-conf
        configMap:
          name: flyway-conf
  backoffLimit: 4
