spec:
  template:
    spec:
      containers:
      - name: grafana
        env:
          - name: GF_SMTP_ENABLED
            value: "true"
          - name: GF_SMTP_FROM_ADDRESS
            value: "your_mail_from_address"
          - name: GF_SMTP_FROM_NAME
            value: "Grafana monitoring"
          - name: GF_SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: notifications-smtp
                key: host
          - name: GF_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notifications-smtp
                key: password
          - name: GF_SMTP_USER
            valueFrom:
              secretKeyRef:
                name: notifications-smtp
                key: user
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-smtp-config