apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-app
  namespace: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerting-app
  template:
    metadata:
      labels:
        app: alerting-app
    spec:
      containers:
      - name: alerting-app
        image: gcr.io/parabolic-hook-437914-f3/number-api:v1
        ports:
        - containerPort: 8080
