name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

    - name: apply migrations to the database
      run: |
        kubectl apply -f server/k8s/flyway_migrate_job.yaml -n pg-ns
        kubectl wait --timeout=30s --for=condition=Complete -f server/k8s/flyway_migrate_job.yaml  -n pg-ns

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/alerting-platform:$(git rev-parse --short HEAD)" -f server/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/alerting-platform:$(git rev-parse --short HEAD)"

    - name: Deploy to Kubernetes
      run: |
        kubectl rollout restart statefulset/alerting-app -n pg-ns --image ${{ secrets.DOCKER_USERNAME }}/alerting-platform:$(git rev-parse --short HEAD)"
