name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 2-server-code

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t unit-tests -f test/unit/Dockerfile .

    - name: Run Docker container
      run: |
        docker run unit-tests
